---
AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: image linker application

Mappings:
  ConfigsMap:
    Table:
      Name: image-linker-files

Resources:

  FilesS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: image-linker-files

  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [ConfigsMap, Table, Name]
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  SaveFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: functions/save-file/
      Tracing: Active
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutBucketNotification
              Resource: !Sub "arn:aws:s3:::image-linker-files*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/image-linker-files'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref FilesS3Bucket
            Events: s3:ObjectCreated:Put

  SaveFileLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SaveFileFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt FilesS3Bucket.Arn
